name: Playwright Manual Tests

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of test to run (regression, smoke, or all browsers)'
        required: true
        type: choice
        options:
          - regression
          - smoke
          - allbrowsers

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Cache the node_modules folder, including Playwright dependencies
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Cache the Playwright browsers directory
      - name: Cache Playwright Browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          QASE_TOKEN: ${{ secrets.QASE_TOKEN }}
        run: |
          if [ "${{ github.event.inputs.test_type }}" == "regression" ]; then
            npm run test:regression
          elif [ "${{ github.event.inputs.test_type }}" == "smoke" ]; then
            npm run test:smoke
          elif [ "${{ github.event.inputs.test_type }}" == "allbrowsers" ]; then
            npm run test:allbrowsers
          else
            echo "Invalid test type specified. Exiting."
            exit 1
          fi

      - name: Upload Playwright JSON Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: results.json
          retention-days: 30

      - uses: daun/playwright-report-summary@v3
        if: always()
        with:
          report-file: results.json

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
